title = "IngeScape"
baseURL = "https://ingescape.com"
tags = ["software bus", "interactive environments"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "ingescape"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
tagline = "IngeScape"
author = "IngeScape"
description = "Flexible and robust platform for heterogeneous distributed software"
logoBig = "/images/osprey-logo.png"
logoSmall = "/images/osprey-logo.png"
favicon = "favicon.ico"
opengraphImage = "/images/osprey.png"
twitter = "ingescape"
linkedin = "ingescape"
github = ""
facebook = ""
email = ""
googleTagManager = ""
highlightJS = true
copyright = true
credit = false
customCSS = false
cacheBustCSS = false
cacheBustJS = false
ajaxFormspree = true

[[menu.main]]
name = "About"
url  = "/#about"
weight = 1
[[menu.main]]
name = "Work"
url  = "/#work"
weight = 2
[[menu.main]]
name = "Blog"
url  = "/#blog"
weight = 3
[[menu.main]]
name = "Contact"
url  = "/#contact"
weight = 4
