baseurl = "https://ingescape.com/"
title = "IngeScape"
theme = "hugo-universal"
themesDir = "./themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
name = "Works"
url  = "/categories/works/"
weight = 2

[[menu.main]]
    name = "Learn"
    url  = "/categories/learn/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Email"
    url = "mailto:contact@ingescape.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "IngeScape"
    defaultKeywords = ["software bus", "interactive environments", "distributed software"]
    defaultDescription = "distributed software made easy (and powerful)"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyDhggMjJqncax4DRagJUzd46g7RK3yXb1M"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "contact@ingescape.com"

about_us = "<p>ingeScape is developped by <a href=\"https://ingenuity.io\">Ingenuity i/o</a> based in Toulouse, France and by the <a href=\"http://www.estia.fr/entreprises/plateformes-techniques.html\">PEPSS</a> platform at <a href=\"http://www.estia.fr\">ESTIA</a> in Bidart, France.</p>"
    copyright = "Copyright (c) 2018, Ingenuity i/o; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "imgages/test2.png"
    address = """<p><strong>Ingenuity i/o</strong>
        <br>16 avenue de l'Europe
        <br>31520 Ramonville Saint-Agne
        <br><strong>France</strong>
      </p>
      """
latitude = "43.552348"
longitude = "1.490556"

[Permalinks]
    blog = "/blog/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
text = """<p class="hidden-sm hidden-xs">Contact us on <a href=\"tel:+33 9 72 63 38 50\">+33 9 72 63 38 50</a> or <a href=\"mailto:contact@ingescape.com\">contact@ingescape.com</a></p>
<p class="hidden-md hidden-lg"><a href="tel:+33 9 72 63 38 50" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
<a href="mailto:contact@ingescape.com" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Made with ingeScape"
    subtitle = "ingeScape is used in many different contexts extending from R&D activities to fully operational solutions. Various ingeScape environments can be found in aeronautics, rails, energy, defense & many more... <a href=\"/categories/works/\">See all works</a>"

[params.see_more]
    enable = true
    icon = "fa fa-rocket"
    title = "Interested in trying ingeScape, getting training or professional service?"
    subtitle = "Our expert team is here to help you design and realize your projects."
    link_url = "/contact"
    link_text = "Contact us"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Discover and learn ingeScape"
    subtitle = "Here are some articles to discover and learn the many facets of ingeScape. <a href=\"/categories/learn/\">See all articles</a>"
